### ISSUE TITLE
Request for the addition of Santali (Ol Chiki) language 

### ISSUE THREAD

**Issue by Prasanta-Hembram** [abdheshnayak/typing-guru#1]
Hi, I request the addition of the Santali language. Can you guide me through the process of adding a new language for typing practice?

**Comment by abdheshnayak** [comment]
Please check https://github.com/abdheshnayak/typing-guru/blob/main/CONTRIBUTING.md for that.

**Comment by Prasanta-Hembram** [comment]
Thanks @abdheshnayak
